// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// An Actor represents an entity that performed an action. For example, an actor
/// could be a user who posted a comment on a support case, a user who
/// uploaded an attachment, or a service account that created a support case.
public struct Actor: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The name to display for the actor. If not provided, it is inferred from
  /// credentials supplied during case creation. When an email is provided, a
  /// display name must also be provided. This will be obfuscated if the user
  /// is a Google Support agent.
  public var displayName: Swift.String = Swift.String()

  /// The email address of the actor. If not provided, it is inferred from the
  /// credentials supplied during case creation. When a name is provided, an
  /// email must also be provided. If the user is a Google Support agent, this is
  /// obfuscated.
  ///
  /// This field is deprecated. Use `username` instead.
  @available(*, deprecated)
  public var email: Swift.String = Swift.String()

  /// Output only. Whether the actor is a Google support actor.
  public var googleSupport: Swift.Bool = Swift.Bool()

  /// Output only. The username of the actor. It may look like an email or other
  /// format provided by the identity provider. If not provided, it is inferred
  /// from the credentials supplied. When a name is provided, a username must
  /// also be provided. If the user is a Google Support agent, this will not be
  /// set.
  public var username: Swift.String = Swift.String()

  /// Initialize a new instance of `Actor`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Actor().with { $0.displayName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.support.v2.Actor"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
