// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// An Actor represents an entity that performed an action. For example, an actor
/// could be a user who posted a comment on a support case, a user who
/// uploaded an attachment, or a service account that created a support case.
public struct Actor: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The name to display for the actor. If not provided, it is inferred from
  /// credentials supplied during case creation. When an email is provided, a
  /// display name must also be provided. This will be obfuscated if the user
  /// is a Google Support agent.
  public var displayName: Swift.String = Swift.String()

  /// The email address of the actor. If not provided, it is inferred from the
  /// credentials supplied during case creation. When a name is provided, an
  /// email must also be provided. If the user is a Google Support agent, this is
  /// obfuscated.
  ///
  /// This field is deprecated. Use `username` instead.
  @available(*, deprecated)
  public var email: Swift.String = Swift.String()

  /// Output only. Whether the actor is a Google support actor.
  public var googleSupport: Swift.Bool = Swift.Bool()

  /// Output only. The username of the actor. It may look like an email or other
  /// format provided by the identity provider. If not provided, it is inferred
  /// from the credentials supplied. When a name is provided, a username must
  /// also be provided. If the user is a Google Support agent, this will not be
  /// set.
  public var username: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `Actor`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Actor().with { $0.displayName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let displayName = CodingKeys(stringValue: "displayName")
    static let email = CodingKeys(stringValue: "email")
    static let googleSupport = CodingKeys(stringValue: "googleSupport")
    static let username = CodingKeys(stringValue: "username")

    static let _knownKeys: Set<Swift.String> = [
      "displayName",
      "email",
      "googleSupport",
      "username",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .email) {
      self.email = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .googleSupport) {
      self.googleSupport = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .username) {
      self.username = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.email, forKey: .email)
    try container.encode(self.googleSupport, forKey: .googleSupport)
    try container.encode(self.username, forKey: .username)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.support.v2.Actor"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
