// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// An Attachment contains metadata about a file that was uploaded to a
/// case - it is NOT a file itself. That being said, the name of an Attachment
/// object can be used to download its accompanying file through the
/// `media.download` endpoint.
///
/// While attachments can be uploaded in the console at the
/// same time as a comment, they're associated on a "case" level, not a
/// "comment" level.
public struct Attachment: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. Identifier. The resource name of the attachment.
  public var name: Swift.String = Swift.String()

  /// Output only. The time at which the attachment was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The user who uploaded the attachment. Note, the name and email
  /// will be obfuscated if the attachment was uploaded by Google support.
  public var creator: Actor? = nil

  /// The filename of the attachment (e.g. `"graph.jpg"`).
  public var filename: Swift.String = Swift.String()

  /// Output only. The MIME type of the attachment (e.g. text/plain).
  public var mimeType: Swift.String = Swift.String()

  /// Output only. The size of the attachment in bytes.
  public var sizeBytes: Swift.Int64 = Swift.Int64()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `Attachment`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Attachment().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let creator = CodingKeys(stringValue: "creator")
    static let filename = CodingKeys(stringValue: "filename")
    static let mimeType = CodingKeys(stringValue: "mimeType")
    static let sizeBytes = CodingKeys(stringValue: "sizeBytes")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "creator",
      "filename",
      "mimeType",
      "sizeBytes",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .createTime)
    self.creator = try container.decodeIfPresent(Actor.self, forKey: .creator)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .filename) {
      self.filename = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .mimeType) {
      self.mimeType = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .sizeBytes) {
      self.sizeBytes = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.creator, forKey: .creator)
    try container.encode(self.filename, forKey: .filename)
    try container.encode(self.mimeType, forKey: .mimeType)
    try container.encode(self.sizeBytes, forKey: .sizeBytes)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.support.v2.Attachment"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
