// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A Case is an object that contains the details of a support case. It
/// contains fields for the time it was created, its priority, its
/// classification, and more. Cases can also have comments and attachments that
/// get added over time.
///
/// A case is parented by a Google Cloud organization or project.
///
/// Organizations are identified by a number, so the name of a case parented by
/// an organization would look like this:
///
/// ```
/// organizations/123/cases/456
/// ```
///
/// Projects have two unique identifiers, an ID and a number, and they look like
/// this:
///
/// ```
/// projects/abc/cases/456
/// ```
///
/// ```
/// projects/123/cases/456
/// ```
///
/// You can use either of them when calling the API. To learn more
/// about project identifiers, see [AIP-2510](https://google.aip.dev/cloud/2510).
public struct Case: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Identifier. The resource name for the case.
  public var name: Swift.String = Swift.String()

  /// The short summary of the issue reported in this case.
  public var displayName: Swift.String = Swift.String()

  /// A broad description of the issue.
  public var description: Swift.String = Swift.String()

  /// The issue classification applicable to this case.
  public var classification: CaseClassification? = nil

  /// The timezone of the user who created the support case.
  /// It should be in a format IANA recognizes: https://www.iana.org/time-zones.
  /// There is no additional validation done by the API.
  public var timeZone: Swift.String = Swift.String()

  /// The email addresses to receive updates on this case.
  public var subscriberEmailAddresses: [Swift.String] = []

  /// Output only. The current status of the support case.
  public var state: Case.State = Case.State()

  /// Output only. The time this case was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The time this case was last updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// The user who created the case.
  ///
  /// Note: The name and email will be obfuscated if the case was created by
  /// Google Support.
  public var creator: Actor? = nil

  /// A user-supplied email address to send case update notifications for. This
  /// should only be used in BYOID flows, where we cannot infer the user's email
  /// address directly from their EUCs.
  public var contactEmail: Swift.String = Swift.String()

  /// Whether the case is currently escalated.
  public var escalated: Swift.Bool = Swift.Bool()

  /// Whether this case was created for internal API testing and should not be
  /// acted on by the support team.
  public var testCase: Swift.Bool = Swift.Bool()

  /// The language the user has requested to receive support in. This should be a
  /// BCP 47 language code (e.g., `"en"`, `"zh-CN"`, `"zh-TW"`, `"ja"`, `"ko"`).
  /// If no language or an unsupported language is specified, this field defaults
  /// to English (en).
  ///
  /// Language selection during case creation may affect your available support
  /// options. For a list of supported languages and their support working hours,
  /// see: https://cloud.google.com/support/docs/language-working-hours
  public var languageCode: Swift.String = Swift.String()

  /// The priority of this case.
  public var priority: Case.Priority = Case.Priority()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `Case`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Case().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let description = CodingKeys(stringValue: "description")
    static let classification = CodingKeys(stringValue: "classification")
    static let timeZone = CodingKeys(stringValue: "timeZone")
    static let subscriberEmailAddresses = CodingKeys(stringValue: "subscriberEmailAddresses")
    static let state = CodingKeys(stringValue: "state")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let creator = CodingKeys(stringValue: "creator")
    static let contactEmail = CodingKeys(stringValue: "contactEmail")
    static let escalated = CodingKeys(stringValue: "escalated")
    static let testCase = CodingKeys(stringValue: "testCase")
    static let languageCode = CodingKeys(stringValue: "languageCode")
    static let priority = CodingKeys(stringValue: "priority")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "displayName",
      "description",
      "classification",
      "timeZone",
      "subscriberEmailAddresses",
      "state",
      "createTime",
      "updateTime",
      "creator",
      "contactEmail",
      "escalated",
      "testCase",
      "languageCode",
      "priority",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    self.classification = try container.decodeIfPresent(
      CaseClassification.self, forKey: .classification)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .timeZone) {
      self.timeZone = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String].self, forKey: .subscriberEmailAddresses)
    {
      self.subscriberEmailAddresses = value
    }
    if let value = try container.decodeIfPresent(Case.State.self, forKey: .state) {
      self.state = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .updateTime)
    self.creator = try container.decodeIfPresent(Actor.self, forKey: .creator)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .contactEmail) {
      self.contactEmail = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .escalated) {
      self.escalated = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .testCase) {
      self.testCase = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .languageCode) {
      self.languageCode = value
    }
    if let value = try container.decodeIfPresent(Case.Priority.self, forKey: .priority) {
      self.priority = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.description, forKey: .description)
    try container.encodeIfPresent(self.classification, forKey: .classification)
    try container.encode(self.timeZone, forKey: .timeZone)
    try container.encode(self.subscriberEmailAddresses, forKey: .subscriberEmailAddresses)
    try container.encode(self.state, forKey: .state)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encodeIfPresent(self.creator, forKey: .creator)
    try container.encode(self.contactEmail, forKey: .contactEmail)
    try container.encode(self.escalated, forKey: .escalated)
    try container.encode(self.testCase, forKey: .testCase)
    try container.encode(self.languageCode, forKey: .languageCode)
    try container.encode(self.priority, forKey: .priority)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The status of a support case.
  public enum State: Codable, Equatable, Sendable {
    /// Case is in an unknown state.
    case unspecified
    /// The case has been created but no one is assigned to work on it yet.
    case new
    /// The case is currently being handled by Google support.
    case inProgressGoogleSupport
    /// Google is waiting for a response.
    case actionRequired
    /// A solution has been offered for the case, but it isn't yet closed.
    case solutionProvided
    /// The case has been resolved.
    case closed
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .new: return 1
      case .inProgressGoogleSupport: return 2
      case .actionRequired: return 3
      case .solutionProvided: return 4
      case .closed: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .new: return "NEW"
      case .inProgressGoogleSupport: return "IN_PROGRESS_GOOGLE_SUPPORT"
      case .actionRequired: return "ACTION_REQUIRED"
      case .solutionProvided: return "SOLUTION_PROVIDED"
      case .closed: return "CLOSED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "NEW": self = .new
      case "IN_PROGRESS_GOOGLE_SUPPORT": self = .inProgressGoogleSupport
      case "ACTION_REQUIRED": self = .actionRequired
      case "SOLUTION_PROVIDED": self = .solutionProvided
      case "CLOSED": self = .closed
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .new
      case 2: self = .inProgressGoogleSupport
      case 3: self = .actionRequired
      case 4: self = .solutionProvided
      case 5: self = .closed
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .new: return try container.encode("NEW")
      case .inProgressGoogleSupport: return try container.encode("IN_PROGRESS_GOOGLE_SUPPORT")
      case .actionRequired: return try container.encode("ACTION_REQUIRED")
      case .solutionProvided: return try container.encode("SOLUTION_PROVIDED")
      case .closed: return try container.encode("CLOSED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The case Priority. P0 is most urgent and P4 the least.
  public enum Priority: Codable, Equatable, Sendable {
    /// Priority is undefined or has not been set yet.
    case unspecified
    /// Extreme impact on a production service. Service is hard down.
    case p0
    /// Critical impact on a production service. Service is currently unusable.
    case p1
    /// Severe impact on a production service. Service is usable but greatly
    /// impaired.
    case p2
    /// Medium impact on a production service.  Service is available, but
    /// moderately impaired.
    case p3
    /// General questions or minor issues.  Production service is fully
    /// available.
    case p4
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .p0: return 1
      case .p1: return 2
      case .p2: return 3
      case .p3: return 4
      case .p4: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PRIORITY_UNSPECIFIED"
      case .p0: return "P0"
      case .p1: return "P1"
      case .p2: return "P2"
      case .p3: return "P3"
      case .p4: return "P4"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Priority/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PRIORITY_UNSPECIFIED": self = .unspecified
      case "P0": self = .p0
      case "P1": self = .p1
      case "P2": self = .p2
      case "P3": self = .p3
      case "P4": self = .p4
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Priority/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .p0
      case 2: self = .p1
      case 3: self = .p2
      case 4: self = .p3
      case 5: self = .p4
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("PRIORITY_UNSPECIFIED")
      case .p0: return try container.encode("P0")
      case .p1: return try container.encode("P1")
      case .p2: return try container.encode("P2")
      case .p3: return try container.encode("P3")
      case .p4: return try container.encode("P4")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.support.v2.Case"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
