// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleWKT
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class CaseServiceLogging: CaseServiceStub {
    let inner: any CaseServiceStub
    let logger: Logger

    public init(_ inner: any CaseServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-support-v2"
      logger[metadataKey: "gcp.client.service"] = "cloudsupport"
      logger[metadataKey: "gcp.experimental.swift.client"] = "CaseService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func getCase(
      request: GetCaseRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSupportV2.Case {
      try await self._intercept(
        request: request,
        options: options,
        name: "getCase",
        action: {
          (r: GetCaseRequest, o: GoogleGax.RequestOptions) async throws -> GoogleCloudSupportV2.Case
          in
          return try await self.inner.getCase(request: r, options: o)
        })
    }

    public func listCases(
      request: ListCasesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSupportV2.ListCasesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listCases",
        action: {
          (r: ListCasesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSupportV2.ListCasesResponse
          in
          return try await self.inner.listCases(request: r, options: o)
        })
    }

    public func searchCases(
      request: SearchCasesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSupportV2.SearchCasesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "searchCases",
        action: {
          (r: SearchCasesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSupportV2.SearchCasesResponse
          in
          return try await self.inner.searchCases(request: r, options: o)
        })
    }

    public func createCase(
      request: CreateCaseRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSupportV2.Case {
      try await self._intercept(
        request: request,
        options: options,
        name: "createCase",
        action: {
          (r: CreateCaseRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSupportV2.Case
          in
          return try await self.inner.createCase(request: r, options: o)
        })
    }

    public func updateCase(
      request: UpdateCaseRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSupportV2.Case {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateCase",
        action: {
          (r: UpdateCaseRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSupportV2.Case
          in
          return try await self.inner.updateCase(request: r, options: o)
        })
    }

    public func escalateCase(
      request: EscalateCaseRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSupportV2.Case {
      try await self._intercept(
        request: request,
        options: options,
        name: "escalateCase",
        action: {
          (r: EscalateCaseRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSupportV2.Case
          in
          return try await self.inner.escalateCase(request: r, options: o)
        })
    }

    public func closeCase(
      request: CloseCaseRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSupportV2.Case {
      try await self._intercept(
        request: request,
        options: options,
        name: "closeCase",
        action: {
          (r: CloseCaseRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSupportV2.Case
          in
          return try await self.inner.closeCase(request: r, options: o)
        })
    }

    public func searchCaseClassifications(
      request: SearchCaseClassificationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSupportV2.SearchCaseClassificationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "searchCaseClassifications",
        action: {
          (r: SearchCaseClassificationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSupportV2.SearchCaseClassificationsResponse
          in
          return try await self.inner.searchCaseClassifications(request: r, options: o)
        })
    }
  }
}
