// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

/// A service to manage file attachments for Google Cloud support cases.
///
/// @Snippet(path: "CaseAttachmentServiceQuickstart")
public final class CaseAttachmentServiceClient: Clients.CaseAttachmentServiceProtocol, Sendable {
  let inner: any Clients.CaseAttachmentServiceStub

  /// Creates a new `CaseAttachmentServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.CaseAttachmentServiceStub = try Clients.CaseAttachmentServiceTransport(
      options)
    inner = Clients.CaseAttachmentServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.CaseAttachmentServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// List all the attachments associated with a support case.
  ///
  /// @Snippet(path: "CaseAttachmentService_ListAttachments")
  public func listAttachments(
    request: ListAttachmentsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSupportV2.ListAttachmentsResponse {
    try await self.inner.listAttachments(request: request, options: options)
  }

  /// List all the attachments associated with a support case.
  ///
  /// @Snippet(path: "CaseAttachmentService_ListAttachments")
  public func listAttachments(
    byItem: ListAttachmentsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Attachment, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudSupportV2.ListAttachmentsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listAttachments(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Retrieve an attachment associated with a support case.
  ///
  /// EXAMPLES:
  ///
  /// cURL:
  ///
  /// ```shell
  /// attachment="projects/some-project/cases/23598314/attachments/0684M00000P3h1fQAB"
  /// curl \
  ///   --header "Authorization: Bearer $(gcloud auth print-access-token)" \
  ///   "https://cloudsupport.googleapis.com/v2/$attachment"
  /// ```
  ///
  /// Python:
  ///
  /// ```python
  /// import googleapiclient.discovery
  ///
  /// api_version = "v2"
  /// supportApiService = googleapiclient.discovery.build(
  ///     serviceName="cloudsupport",
  ///     version=api_version,
  ///     discoveryServiceUrl=f"https://cloudsupport.googleapis.com/$discovery/rest?version={api_version}",
  /// )
  /// request = (
  ///     supportApiService.cases()
  ///     .attachments()
  ///     .get(name="projects/some-project/cases/43595344/attachments/0684M00000P3h1fQAB")
  /// )
  /// print(request.execute())
  /// ```
  ///
  /// @Snippet(path: "CaseAttachmentService_GetAttachment")
  public func getAttachment(
    request: GetAttachmentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSupportV2.Attachment {
    try await self.inner.getAttachment(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `CaseAttachmentServiceClient`.
  ///
  /// To mock `CaseAttachmentServiceClient` change your functions to receive
  /// `some CaseAttachmentServiceProtocol` or `any CaseAttachmentServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol CaseAttachmentServiceProtocol {
    /// See `CaseAttachmentServiceClient.listAttachments`.
    func listAttachments(request: ListAttachmentsRequest) async throws
      -> GoogleCloudSupportV2.ListAttachmentsResponse

    /// See `CaseAttachmentServiceClient.listAttachments`.
    func listAttachments(
      byItem: ListAttachmentsRequest
    ) throws -> any AsyncSequence<Attachment, Swift.Error>

    /// See `CaseAttachmentServiceClient.listAttachments`.
    func listAttachments(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Attachment, Swift.Error>

    /// See `CaseAttachmentServiceClient.getAttachment`.
    func getAttachment(request: GetAttachmentRequest) async throws
      -> GoogleCloudSupportV2.Attachment

    /// See `CaseAttachmentServiceClient.getAttachment`.
    func getAttachment(
      name: Swift.String,
    ) async throws -> GoogleCloudSupportV2.Attachment

    /// See `CaseAttachmentServiceClient.listAttachments`.
    func listAttachments(
      request: ListAttachmentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSupportV2.ListAttachmentsResponse

    /// See `CaseAttachmentServiceClient.listAttachments`.
    func listAttachments(
      byItem: ListAttachmentsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Attachment, Swift.Error>

    /// See `CaseAttachmentServiceClient.getAttachment`.
    func getAttachment(
      request: GetAttachmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSupportV2.Attachment
  }
}

// Default implementations
extension Clients.CaseAttachmentServiceProtocol {
  public func listAttachments(request: ListAttachmentsRequest) async throws
    -> GoogleCloudSupportV2.ListAttachmentsResponse
  {
    try await self.listAttachments(request: request, options: .init())
  }

  public func listAttachments(
    request: ListAttachmentsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSupportV2.ListAttachmentsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listAttachments(
    byItem: ListAttachmentsRequest
  ) throws -> any AsyncSequence<Attachment, Swift.Error> {
    try self.listAttachments(byItem: byItem, options: .init())
  }

  public func listAttachments(
    byItem: ListAttachmentsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Attachment, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudSupportV2.ListAttachmentsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listAttachments(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Attachment, Swift.Error> {
    let request = ListAttachmentsRequest().with {
      $0.parent = parent
    }
    return try self.listAttachments(byItem: request)
  }

  public func getAttachment(request: GetAttachmentRequest) async throws
    -> GoogleCloudSupportV2.Attachment
  {
    try await self.getAttachment(request: request, options: .init())
  }

  public func getAttachment(
    request: GetAttachmentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSupportV2.Attachment {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getAttachment(
    name: Swift.String,
  ) async throws -> GoogleCloudSupportV2.Attachment {
    let request = GetAttachmentRequest().with {
      $0.name = name
    }
    return try await self.getAttachment(request: request)
  }
}
