// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

extension Clients {
  final class CaseServiceRetry: CaseServiceStub {
    let inner: any CaseServiceStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any CaseServiceStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func getCase(
      request: GetCaseRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSupportV2.Case {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetCaseRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSupportV2.Case
          in
          return try await self.inner.getCase(request: r, options: o)
        })
    }

    public func listCases(
      request: ListCasesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSupportV2.ListCasesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListCasesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSupportV2.ListCasesResponse
          in
          return try await self.inner.listCases(request: r, options: o)
        })
    }

    public func searchCases(
      request: SearchCasesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSupportV2.SearchCasesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: SearchCasesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSupportV2.SearchCasesResponse
          in
          return try await self.inner.searchCases(request: r, options: o)
        })
    }

    public func createCase(
      request: CreateCaseRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSupportV2.Case {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateCaseRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSupportV2.Case
          in
          return try await self.inner.createCase(request: r, options: o)
        })
    }

    public func updateCase(
      request: UpdateCaseRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSupportV2.Case {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateCaseRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSupportV2.Case
          in
          return try await self.inner.updateCase(request: r, options: o)
        })
    }

    public func escalateCase(
      request: EscalateCaseRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSupportV2.Case {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: EscalateCaseRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSupportV2.Case
          in
          return try await self.inner.escalateCase(request: r, options: o)
        })
    }

    public func closeCase(
      request: CloseCaseRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSupportV2.Case {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CloseCaseRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSupportV2.Case
          in
          return try await self.inner.closeCase(request: r, options: o)
        })
    }

    public func searchCaseClassifications(
      request: SearchCaseClassificationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSupportV2.SearchCaseClassificationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: SearchCaseClassificationsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSupportV2.SearchCaseClassificationsResponse
          in
          return try await self.inner.searchCaseClassifications(request: r, options: o)
        })
    }
  }
}
