// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

extension Clients {
  final class CommentServiceRetry: CommentServiceStub {
    let inner: any CommentServiceStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any CommentServiceStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func listComments(
      request: ListCommentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSupportV2.ListCommentsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListCommentsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSupportV2.ListCommentsResponse
          in
          return try await self.inner.listComments(request: r, options: o)
        })
    }

    public func createComment(
      request: CreateCommentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSupportV2.Comment {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateCommentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSupportV2.Comment
          in
          return try await self.inner.createComment(request: r, options: o)
        })
    }

    public func getComment(
      request: GetCommentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSupportV2.Comment {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetCommentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSupportV2.Comment
          in
          return try await self.inner.getComment(request: r, options: o)
        })
    }
  }
}
