// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A comment associated with a support case.
///
/// Case comments are the primary way for Google Support to communicate with a
/// user who has opened a case. When a user responds to Google Support, the
/// user's responses also appear as comments.
public struct Comment: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. Identifier. The resource name of the comment.
  public var name: Swift.String = Swift.String()

  /// Output only. The time when the comment was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The user or Google Support agent who created the comment.
  public var creator: Actor? = nil

  /// The full comment body.
  ///
  /// Maximum of 12800 characters.
  public var body: Swift.String = Swift.String()

  /// Output only. DEPRECATED. DO NOT USE.
  ///
  /// A duplicate of the `body` field.
  ///
  /// This field is only present for legacy reasons.
  @available(*, deprecated)
  public var plainTextBody: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `Comment`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Comment().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let creator = CodingKeys(stringValue: "creator")
    static let body = CodingKeys(stringValue: "body")
    static let plainTextBody = CodingKeys(stringValue: "plainTextBody")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "creator",
      "body",
      "plainTextBody",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .createTime)
    self.creator = try container.decodeIfPresent(Actor.self, forKey: .creator)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .body) {
      self.body = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .plainTextBody) {
      self.plainTextBody = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.creator, forKey: .creator)
    try container.encode(self.body, forKey: .body)
    try container.encode(self.plainTextBody, forKey: .plainTextBody)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.support.v2.Comment"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
