// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleWKT
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class CommentServiceLogging: CommentServiceStub {
    let inner: any CommentServiceStub
    let logger: Logger

    public init(_ inner: any CommentServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-support-v2"
      logger[metadataKey: "gcp.client.service"] = "cloudsupport"
      logger[metadataKey: "gcp.experimental.swift.client"] = "CommentService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listComments(
      request: ListCommentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSupportV2.ListCommentsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listComments",
        action: {
          (r: ListCommentsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSupportV2.ListCommentsResponse
          in
          return try await self.inner.listComments(request: r, options: o)
        })
    }

    public func createComment(
      request: CreateCommentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSupportV2.Comment {
      try await self._intercept(
        request: request,
        options: options,
        name: "createComment",
        action: {
          (r: CreateCommentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSupportV2.Comment
          in
          return try await self.inner.createComment(request: r, options: o)
        })
    }

    public func getComment(
      request: GetCommentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSupportV2.Comment {
      try await self._intercept(
        request: request,
        options: options,
        name: "getComment",
        action: {
          (r: GetCommentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSupportV2.Comment
          in
          return try await self.inner.getComment(request: r, options: o)
        })
    }
  }
}
