// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// An escalation of a support case.
public struct Escalation: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The reason why the Case is being escalated.
  public var reason: Escalation.Reason = Escalation.Reason()

  /// Required. A free text description to accompany the `reason` field above.
  /// Provides additional context on why the case is being escalated.
  public var justification: Swift.String = Swift.String()

  /// Initialize a new instance of `Escalation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Escalation().with { $0.reason = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// An enum detailing the possible reasons a case may be escalated.
  public enum Reason: Codable, Equatable, Sendable {
    /// The escalation reason is in an unknown state or has not been specified.
    case unspecified
    /// The case is taking too long to resolve.
    case resolutionTime
    /// The support agent does not have the expertise required to successfully
    /// resolve the issue.
    case technicalExpertise
    /// The issue is having a significant business impact.
    case businessImpact
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .resolutionTime: return 1
      case .technicalExpertise: return 2
      case .businessImpact: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "REASON_UNSPECIFIED"
      case .resolutionTime: return "RESOLUTION_TIME"
      case .technicalExpertise: return "TECHNICAL_EXPERTISE"
      case .businessImpact: return "BUSINESS_IMPACT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Reason/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "REASON_UNSPECIFIED": self = .unspecified
      case "RESOLUTION_TIME": self = .resolutionTime
      case "TECHNICAL_EXPERTISE": self = .technicalExpertise
      case "BUSINESS_IMPACT": self = .businessImpact
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Reason/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .resolutionTime
      case 2: self = .technicalExpertise
      case 3: self = .businessImpact
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .resolutionTime: return try container.encode(1)
      case .technicalExpertise: return try container.encode(2)
      case .businessImpact: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.support.v2.Escalation"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
