// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request message for ListSupportEventSubscriptions.
public struct ListSupportEventSubscriptionsRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The fully qualified name of the Cloud resource to list support
  /// event subscriptions under. Format: organizations/{organization_id}
  public var parent: Swift.String = Swift.String()

  /// Optional. Filter expression based on AIP-160.
  /// Supported fields:
  /// - pub_sub_topic
  /// - state
  ///
  /// Examples:
  /// - `pub_sub_topic="projects/example-project/topics/example-topic"`
  /// - `state=WORKING`
  /// - `pub_sub_topic="projects/example-project/topics/example-topic" AND
  /// state=WORKING`
  public var filter: Swift.String = Swift.String()

  /// Optional. Whether to show deleted subscriptions. By default, deleted
  /// subscriptions are not returned.
  public var showDeleted: Swift.Bool = Swift.Bool()

  /// Optional. The maximum number of support event subscriptions to return.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A token identifying the page of results to return. If
  /// unspecified, the first page is retrieved.
  ///
  /// When paginating, all other parameters provided to
  /// `ListSupportEventSubscriptions` must match the call that provided the page
  /// token.
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListSupportEventSubscriptionsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListSupportEventSubscriptionsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.support.v2.ListSupportEventSubscriptionsRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
