// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The request message for the ListCases endpoint.
public struct ListCasesRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The name of a parent to list cases under.
  public var parent: Swift.String = Swift.String()

  /// An expression used to filter cases.
  ///
  /// If it's an empty string, then no filtering happens. Otherwise, the endpoint
  /// returns the cases that match the filter.
  ///
  /// Expressions use the following fields separated by `AND` and specified with
  /// `=`:
  ///
  /// - `state`: Can be `OPEN` or `CLOSED`.
  /// - `priority`: Can be `P0`, `P1`, `P2`, `P3`, or `P4`. You
  /// can specify multiple values for priority using the `OR` operator. For
  /// example, `priority=P1 OR priority=P2`.
  /// - `creator.email`: The email address of the case creator.
  ///
  /// EXAMPLES:
  ///
  /// - `state=CLOSED`
  /// - `state=OPEN AND creator.email="tester@example.com"`
  /// - `state=OPEN AND (priority=P0 OR priority=P1)`
  public var filter: Swift.String = Swift.String()

  /// The maximum number of cases fetched with each request. Defaults to 10.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// A token identifying the page of results to return. If unspecified, the
  /// first page is retrieved.
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListCasesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListCasesRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.support.v2.ListCasesRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
