// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The request message for the SearchCases endpoint.
public struct SearchCasesRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The name of the parent resource to search for cases under.
  public var parent: Swift.String = Swift.String()

  /// An expression used to filter cases.
  ///
  /// Expressions use the following fields separated by `AND` and specified with
  /// `=`:
  ///
  /// - `state`: Can be `OPEN` or `CLOSED`.
  /// - `priority`: Can be `P0`, `P1`, `P2`, `P3`, or `P4`. You
  /// can specify multiple values for priority using the `OR` operator. For
  /// example, `priority=P1 OR priority=P2`.
  /// - `creator.email`: The email address of the case creator.
  ///
  /// To search across `displayName`, `description`, and comments, use a global
  /// restriction with no keyword or operator. For example, `"my search"`.
  ///
  /// To search only cases updated after a certain date, use `update_time`
  /// restricted with that particular date, time, and timezone in ISO datetime
  /// format. For example, `update_time>"2020-01-01T00:00:00-05:00"`.
  /// `update_time` only supports the greater than operator (`>`).
  ///
  /// If you are using the `v2` version of the API, you must specify the case
  /// parent in the `parent` field. If you provide an empty `query`, all cases
  /// under the parent resource will be returned.
  ///
  /// If you are using the `v2beta` version of the API, you must specify the case
  /// parent in the `query` field using one of the two fields below, which are
  /// only available for `v2beta`. The `parent` field will be ignored.
  ///
  /// - `organization`: An organization name in the form
  /// `organizations/<organization_id>`.
  /// - `project`: A project name in the form `projects/<project_id>`.
  ///
  /// Examples:
  ///
  /// For `v2`:
  ///
  /// - `state=CLOSED`
  /// - `state=OPEN AND creator.email="tester@example.com"`
  /// - `state=OPEN AND (priority=P0 OR priority=P1)`
  /// - `update_time>"2020-01-01T00:00:00-05:00"`
  ///
  /// For `v2beta`:
  ///
  /// - `organization="organizations/123456789"`
  /// - `project="projects/my-project-id"`
  /// - `project="projects/123456789"`
  /// - `organization="organizations/123456789" AND state=CLOSED`
  /// - `project="projects/my-project-id" AND creator.email="tester@example.com"`
  /// - `project="projects/my-project-id" AND (priority=P0 OR priority=P1)`
  public var query: Swift.String = Swift.String()

  /// The maximum number of cases fetched with each request. The default page
  /// size is 10.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// A token identifying the page of results to return. If unspecified, the
  /// first page is retrieved.
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `SearchCasesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SearchCasesRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.support.v2.SearchCasesRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
