// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A support event subscription.
///
/// You can also manage support event subscriptions using other tools:
///
/// * [`gcloud support
/// support-event-subscriptions`](/sdk/gcloud/reference/support/support-event-subscriptions)
/// (or [`gcloud
/// beta`](/sdk/gcloud/reference/beta/support/support-event-subscriptions)
/// for beta)
/// * [Terraform
/// `google_cloud_support_support_event_subscription`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_support_support_event_subscription)
/// (or [google-beta
/// provider](https://registry.terraform.io/providers/hashicorp/google-beta/latest/docs/resources/cloud_support_support_event_subscription)
/// for beta)
public struct SupportEventSubscription: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. The resource name of the support event subscription.
  public var name: Swift.String = Swift.String()

  /// Required. The name of the Pub/Sub topic to publish notifications to.
  /// Format: projects/{project}/topics/{topic}
  public var pubSubTopic: Swift.String = Swift.String()

  /// Output only. The state of the subscription.
  public var state: SupportEventSubscription.State = SupportEventSubscription.State()

  /// Output only. Reason why subscription is failing. State of subscription
  /// must be FAILING in order for this to have a value.
  public var failureReason: SupportEventSubscription.FailureReason =
    SupportEventSubscription.FailureReason()

  /// Output only. The time at which the subscription was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time at which the subscription was last updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time at which the subscription was deleted.
  public var deleteTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time at which the subscription will be purged.
  public var purgeTime: GoogleCloudWkt.Timestamp? = nil

  /// Initialize a new instance of `SupportEventSubscription`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SupportEventSubscription().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The state of the subscription.
  public enum State: Codable, Equatable, Sendable {
    /// Unspecified state.
    case unspecified
    /// Subscription is active and working.
    case working
    /// Subscription is failing. Notifications cannot be published for some
    /// reason.
    case failing
    /// Subscription has been deleted and is pending purge. Notifications are not
    /// sent for deleted subscriptions. Deleted subscriptions are purged after
    /// their `purge_time` has passed.
    case deleted
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .working: return 1
      case .failing: return 2
      case .deleted: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .working: return "WORKING"
      case .failing: return "FAILING"
      case .deleted: return "DELETED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "WORKING": self = .working
      case "FAILING": self = .failing
      case "DELETED": self = .deleted
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .working
      case 2: self = .failing
      case 3: self = .deleted
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .working: return try container.encode(1)
      case .failing: return try container.encode(2)
      case .deleted: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The reason why the subscription is failing.
  public enum FailureReason: Codable, Equatable, Sendable {
    /// Unspecified failure reason.
    case unspecified
    /// The service account (i.e.
    /// cloud-support-apievents@system.gserviceaccount.com) lacks the permission
    /// to publish to the customer's Pub/Sub topic.
    case permissionDenied
    /// The specified Pub/Sub topic does not exist.
    case topicNotFound
    /// Message failed to publish due to a system-side error.
    case other
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .permissionDenied: return 1
      case .topicNotFound: return 2
      case .other: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "FAILURE_REASON_UNSPECIFIED"
      case .permissionDenied: return "PERMISSION_DENIED"
      case .topicNotFound: return "TOPIC_NOT_FOUND"
      case .other: return "OTHER"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:FailureReason/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "FAILURE_REASON_UNSPECIFIED": self = .unspecified
      case "PERMISSION_DENIED": self = .permissionDenied
      case "TOPIC_NOT_FOUND": self = .topicNotFound
      case "OTHER": self = .other
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:FailureReason/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .permissionDenied
      case 2: self = .topicNotFound
      case 3: self = .other
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .permissionDenied: return try container.encode(1)
      case .topicNotFound: return try container.encode(2)
      case .other: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.support.v2.SupportEventSubscription"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
