// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWKT
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class SupportEventSubscriptionServiceLogging: SupportEventSubscriptionServiceStub {
    let inner: any SupportEventSubscriptionServiceStub
    let logger: Logger

    public init(_ inner: any SupportEventSubscriptionServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-support-v2"
      logger[metadataKey: "gcp.client.service"] = "cloudsupport"
      logger[metadataKey: "gcp.experimental.swift.client"] = "SupportEventSubscriptionService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func createSupportEventSubscription(
      request: CreateSupportEventSubscriptionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSupportV2.SupportEventSubscription {
      try await self._intercept(
        request: request,
        options: options,
        name: "createSupportEventSubscription",
        action: {
          (r: CreateSupportEventSubscriptionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSupportV2.SupportEventSubscription
          in
          return try await self.inner.createSupportEventSubscription(request: r, options: o)
        })
    }

    public func getSupportEventSubscription(
      request: GetSupportEventSubscriptionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSupportV2.SupportEventSubscription {
      try await self._intercept(
        request: request,
        options: options,
        name: "getSupportEventSubscription",
        action: {
          (r: GetSupportEventSubscriptionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSupportV2.SupportEventSubscription
          in
          return try await self.inner.getSupportEventSubscription(request: r, options: o)
        })
    }

    public func listSupportEventSubscriptions(
      request: ListSupportEventSubscriptionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSupportV2.ListSupportEventSubscriptionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listSupportEventSubscriptions",
        action: {
          (r: ListSupportEventSubscriptionsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSupportV2.ListSupportEventSubscriptionsResponse
          in
          return try await self.inner.listSupportEventSubscriptions(request: r, options: o)
        })
    }

    public func updateSupportEventSubscription(
      request: UpdateSupportEventSubscriptionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSupportV2.SupportEventSubscription {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateSupportEventSubscription",
        action: {
          (r: UpdateSupportEventSubscriptionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSupportV2.SupportEventSubscription
          in
          return try await self.inner.updateSupportEventSubscription(request: r, options: o)
        })
    }

    public func deleteSupportEventSubscription(
      request: DeleteSupportEventSubscriptionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSupportV2.SupportEventSubscription {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteSupportEventSubscription",
        action: {
          (r: DeleteSupportEventSubscriptionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSupportV2.SupportEventSubscription
          in
          return try await self.inner.deleteSupportEventSubscription(request: r, options: o)
        })
    }

    public func undeleteSupportEventSubscription(
      request: UndeleteSupportEventSubscriptionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSupportV2.SupportEventSubscription {
      try await self._intercept(
        request: request,
        options: options,
        name: "undeleteSupportEventSubscription",
        action: {
          (r: UndeleteSupportEventSubscriptionRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudSupportV2.SupportEventSubscription
          in
          return try await self.inner.undeleteSupportEventSubscription(request: r, options: o)
        })
    }

    public func expungeSupportEventSubscription(
      request: ExpungeSupportEventSubscriptionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "expungeSupportEventSubscription",
        action: {
          (r: ExpungeSupportEventSubscriptionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.expungeSupportEventSubscription(request: r, options: o)
        })
    }
  }
}
