// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

/// Service for managing customer support event subscriptions.
///
/// @Snippet(path: "SupportEventSubscriptionServiceQuickstart")
public class SupportEventSubscriptionServiceClient: Clients.SupportEventSubscriptionServiceProtocol
{
  let inner: any Clients.SupportEventSubscriptionServiceStub

  /// Creates a new `SupportEventSubscriptionServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.SupportEventSubscriptionServiceStub =
      try Clients.SupportEventSubscriptionServiceTransport(options)
    inner = Clients.SupportEventSubscriptionServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.SupportEventSubscriptionServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Creates a support event subscription for an organization.
  ///
  /// @Snippet(path: "SupportEventSubscriptionService_CreateSupportEventSubscription")
  public func createSupportEventSubscription(
    request: CreateSupportEventSubscriptionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSupportV2.SupportEventSubscription {
    try await self.inner.createSupportEventSubscription(request: request, options: options)
  }

  /// Gets a support event subscription.
  ///
  /// @Snippet(path: "SupportEventSubscriptionService_GetSupportEventSubscription")
  public func getSupportEventSubscription(
    request: GetSupportEventSubscriptionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSupportV2.SupportEventSubscription {
    try await self.inner.getSupportEventSubscription(request: request, options: options)
  }

  /// Lists support event subscriptions for an organization.
  ///
  /// @Snippet(path: "SupportEventSubscriptionService_ListSupportEventSubscriptions")
  public func listSupportEventSubscriptions(
    request: ListSupportEventSubscriptionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSupportV2.ListSupportEventSubscriptionsResponse {
    try await self.inner.listSupportEventSubscriptions(request: request, options: options)
  }

  /// Lists support event subscriptions for an organization.
  ///
  /// @Snippet(path: "SupportEventSubscriptionService_ListSupportEventSubscriptions")
  public func listSupportEventSubscriptions(
    byItem: ListSupportEventSubscriptionsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<SupportEventSubscription, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudSupportV2.ListSupportEventSubscriptionsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listSupportEventSubscriptions(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Updates a support event subscription.
  ///
  /// @Snippet(path: "SupportEventSubscriptionService_UpdateSupportEventSubscription")
  public func updateSupportEventSubscription(
    request: UpdateSupportEventSubscriptionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSupportV2.SupportEventSubscription {
    try await self.inner.updateSupportEventSubscription(request: request, options: options)
  }

  /// Soft deletes a support event subscription.
  ///
  /// @Snippet(path: "SupportEventSubscriptionService_DeleteSupportEventSubscription")
  public func deleteSupportEventSubscription(
    request: DeleteSupportEventSubscriptionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSupportV2.SupportEventSubscription {
    try await self.inner.deleteSupportEventSubscription(request: request, options: options)
  }

  /// Undeletes a support event subscription.
  ///
  /// @Snippet(path: "SupportEventSubscriptionService_UndeleteSupportEventSubscription")
  public func undeleteSupportEventSubscription(
    request: UndeleteSupportEventSubscriptionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSupportV2.SupportEventSubscription {
    try await self.inner.undeleteSupportEventSubscription(request: request, options: options)
  }

  /// Expunges a support event subscription.
  ///
  /// EXAMPLES:
  ///
  /// cURL:
  ///
  /// ```shell
  /// support_event_subscription="organizations/123456789/supportEventSubscriptions/abcdef123456"
  /// curl \
  ///   --request POST \
  ///   --header "Authorization: Bearer $(gcloud auth print-access-token)" \
  ///   "https://cloudsupport.googleapis.com/v2/$support_event_subscription:expunge"
  /// ```
  ///
  /// Python:
  ///
  /// ```python
  /// import googleapiclient.discovery
  ///
  /// api_version = "v2"
  /// supportApiService = googleapiclient.discovery.build(
  ///     serviceName="cloudsupport",
  ///     version=api_version,
  ///     discoveryServiceUrl=f"https://cloudsupport.googleapis.com/$discovery/rest?version={api_version}",
  /// )
  ///
  /// request = supportApiService.supportEventSubscriptions().expunge(
  ///     name="organizations/123456789/supportEventSubscriptions/abcdef123456"
  /// )
  /// print(request.execute())
  /// ```
  ///
  /// @Snippet(path: "SupportEventSubscriptionService_ExpungeSupportEventSubscription")
  public func expungeSupportEventSubscription(
    request: ExpungeSupportEventSubscriptionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.expungeSupportEventSubscription(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `SupportEventSubscriptionServiceClient`.
  ///
  /// To mock `SupportEventSubscriptionServiceClient` change your functions to receive
  /// `some SupportEventSubscriptionServiceProtocol` or `any SupportEventSubscriptionServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol SupportEventSubscriptionServiceProtocol {
    /// See `SupportEventSubscriptionServiceClient.createSupportEventSubscription`.
    func createSupportEventSubscription(request: CreateSupportEventSubscriptionRequest) async throws
      -> GoogleCloudSupportV2.SupportEventSubscription

    /// See `SupportEventSubscriptionServiceClient.createSupportEventSubscription`.
    func createSupportEventSubscription(
      parent: Swift.String,
      supportEventSubscription: SupportEventSubscription?,
    ) async throws -> GoogleCloudSupportV2.SupportEventSubscription

    /// See `SupportEventSubscriptionServiceClient.getSupportEventSubscription`.
    func getSupportEventSubscription(request: GetSupportEventSubscriptionRequest) async throws
      -> GoogleCloudSupportV2.SupportEventSubscription

    /// See `SupportEventSubscriptionServiceClient.getSupportEventSubscription`.
    func getSupportEventSubscription(
      name: Swift.String,
    ) async throws -> GoogleCloudSupportV2.SupportEventSubscription

    /// See `SupportEventSubscriptionServiceClient.listSupportEventSubscriptions`.
    func listSupportEventSubscriptions(request: ListSupportEventSubscriptionsRequest) async throws
      -> GoogleCloudSupportV2.ListSupportEventSubscriptionsResponse

    /// See `SupportEventSubscriptionServiceClient.listSupportEventSubscriptions`.
    func listSupportEventSubscriptions(
      byItem: ListSupportEventSubscriptionsRequest
    ) throws -> any AsyncSequence<SupportEventSubscription, Swift.Error>

    /// See `SupportEventSubscriptionServiceClient.listSupportEventSubscriptions`.
    func listSupportEventSubscriptions(
      parent: Swift.String,
    ) throws -> any AsyncSequence<SupportEventSubscription, Swift.Error>

    /// See `SupportEventSubscriptionServiceClient.updateSupportEventSubscription`.
    func updateSupportEventSubscription(request: UpdateSupportEventSubscriptionRequest) async throws
      -> GoogleCloudSupportV2.SupportEventSubscription

    /// See `SupportEventSubscriptionServiceClient.updateSupportEventSubscription`.
    func updateSupportEventSubscription(
      supportEventSubscription: SupportEventSubscription?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> GoogleCloudSupportV2.SupportEventSubscription

    /// See `SupportEventSubscriptionServiceClient.deleteSupportEventSubscription`.
    func deleteSupportEventSubscription(request: DeleteSupportEventSubscriptionRequest) async throws
      -> GoogleCloudSupportV2.SupportEventSubscription

    /// See `SupportEventSubscriptionServiceClient.deleteSupportEventSubscription`.
    func deleteSupportEventSubscription(
      name: Swift.String,
    ) async throws -> GoogleCloudSupportV2.SupportEventSubscription

    /// See `SupportEventSubscriptionServiceClient.undeleteSupportEventSubscription`.
    func undeleteSupportEventSubscription(request: UndeleteSupportEventSubscriptionRequest)
      async throws -> GoogleCloudSupportV2.SupportEventSubscription

    /// See `SupportEventSubscriptionServiceClient.expungeSupportEventSubscription`.
    func expungeSupportEventSubscription(request: ExpungeSupportEventSubscriptionRequest)
      async throws

    /// See `SupportEventSubscriptionServiceClient.expungeSupportEventSubscription`.
    func expungeSupportEventSubscription(
      name: Swift.String,
    ) async throws

    /// See `SupportEventSubscriptionServiceClient.createSupportEventSubscription`.
    func createSupportEventSubscription(
      request: CreateSupportEventSubscriptionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSupportV2.SupportEventSubscription

    /// See `SupportEventSubscriptionServiceClient.getSupportEventSubscription`.
    func getSupportEventSubscription(
      request: GetSupportEventSubscriptionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSupportV2.SupportEventSubscription

    /// See `SupportEventSubscriptionServiceClient.listSupportEventSubscriptions`.
    func listSupportEventSubscriptions(
      request: ListSupportEventSubscriptionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSupportV2.ListSupportEventSubscriptionsResponse

    /// See `SupportEventSubscriptionServiceClient.listSupportEventSubscriptions`.
    func listSupportEventSubscriptions(
      byItem: ListSupportEventSubscriptionsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<SupportEventSubscription, Swift.Error>

    /// See `SupportEventSubscriptionServiceClient.updateSupportEventSubscription`.
    func updateSupportEventSubscription(
      request: UpdateSupportEventSubscriptionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSupportV2.SupportEventSubscription

    /// See `SupportEventSubscriptionServiceClient.deleteSupportEventSubscription`.
    func deleteSupportEventSubscription(
      request: DeleteSupportEventSubscriptionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSupportV2.SupportEventSubscription

    /// See `SupportEventSubscriptionServiceClient.undeleteSupportEventSubscription`.
    func undeleteSupportEventSubscription(
      request: UndeleteSupportEventSubscriptionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSupportV2.SupportEventSubscription

    /// See `SupportEventSubscriptionServiceClient.expungeSupportEventSubscription`.
    func expungeSupportEventSubscription(
      request: ExpungeSupportEventSubscriptionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.SupportEventSubscriptionServiceProtocol {
  public func createSupportEventSubscription(request: CreateSupportEventSubscriptionRequest)
    async throws -> GoogleCloudSupportV2.SupportEventSubscription
  {
    try await self.createSupportEventSubscription(request: request, options: .init())
  }

  public func createSupportEventSubscription(
    request: CreateSupportEventSubscriptionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSupportV2.SupportEventSubscription {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createSupportEventSubscription(
    parent: Swift.String,
    supportEventSubscription: SupportEventSubscription?,
  ) async throws -> GoogleCloudSupportV2.SupportEventSubscription {
    let request = CreateSupportEventSubscriptionRequest().with {
      $0.parent = parent
      $0.supportEventSubscription = supportEventSubscription
    }
    return try await self.createSupportEventSubscription(request: request)
  }

  public func getSupportEventSubscription(request: GetSupportEventSubscriptionRequest) async throws
    -> GoogleCloudSupportV2.SupportEventSubscription
  {
    try await self.getSupportEventSubscription(request: request, options: .init())
  }

  public func getSupportEventSubscription(
    request: GetSupportEventSubscriptionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSupportV2.SupportEventSubscription {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getSupportEventSubscription(
    name: Swift.String,
  ) async throws -> GoogleCloudSupportV2.SupportEventSubscription {
    let request = GetSupportEventSubscriptionRequest().with {
      $0.name = name
    }
    return try await self.getSupportEventSubscription(request: request)
  }

  public func listSupportEventSubscriptions(request: ListSupportEventSubscriptionsRequest)
    async throws -> GoogleCloudSupportV2.ListSupportEventSubscriptionsResponse
  {
    try await self.listSupportEventSubscriptions(request: request, options: .init())
  }

  public func listSupportEventSubscriptions(
    request: ListSupportEventSubscriptionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSupportV2.ListSupportEventSubscriptionsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listSupportEventSubscriptions(
    byItem: ListSupportEventSubscriptionsRequest
  ) throws -> any AsyncSequence<SupportEventSubscription, Swift.Error> {
    try self.listSupportEventSubscriptions(byItem: byItem, options: .init())
  }

  public func listSupportEventSubscriptions(
    byItem: ListSupportEventSubscriptionsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<SupportEventSubscription, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudSupportV2.ListSupportEventSubscriptionsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listSupportEventSubscriptions(
    parent: Swift.String,
  ) throws -> any AsyncSequence<SupportEventSubscription, Swift.Error> {
    let request = ListSupportEventSubscriptionsRequest().with {
      $0.parent = parent
    }
    return try self.listSupportEventSubscriptions(byItem: request)
  }

  public func updateSupportEventSubscription(request: UpdateSupportEventSubscriptionRequest)
    async throws -> GoogleCloudSupportV2.SupportEventSubscription
  {
    try await self.updateSupportEventSubscription(request: request, options: .init())
  }

  public func updateSupportEventSubscription(
    request: UpdateSupportEventSubscriptionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSupportV2.SupportEventSubscription {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateSupportEventSubscription(
    supportEventSubscription: SupportEventSubscription?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> GoogleCloudSupportV2.SupportEventSubscription {
    let request = UpdateSupportEventSubscriptionRequest().with {
      $0.supportEventSubscription = supportEventSubscription
      $0.updateMask = updateMask
    }
    return try await self.updateSupportEventSubscription(request: request)
  }

  public func deleteSupportEventSubscription(request: DeleteSupportEventSubscriptionRequest)
    async throws -> GoogleCloudSupportV2.SupportEventSubscription
  {
    try await self.deleteSupportEventSubscription(request: request, options: .init())
  }

  public func deleteSupportEventSubscription(
    request: DeleteSupportEventSubscriptionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSupportV2.SupportEventSubscription {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteSupportEventSubscription(
    name: Swift.String,
  ) async throws -> GoogleCloudSupportV2.SupportEventSubscription {
    let request = DeleteSupportEventSubscriptionRequest().with {
      $0.name = name
    }
    return try await self.deleteSupportEventSubscription(request: request)
  }

  public func undeleteSupportEventSubscription(request: UndeleteSupportEventSubscriptionRequest)
    async throws -> GoogleCloudSupportV2.SupportEventSubscription
  {
    try await self.undeleteSupportEventSubscription(request: request, options: .init())
  }

  public func undeleteSupportEventSubscription(
    request: UndeleteSupportEventSubscriptionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSupportV2.SupportEventSubscription {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func expungeSupportEventSubscription(request: ExpungeSupportEventSubscriptionRequest)
    async throws
  {
    try await self.expungeSupportEventSubscription(request: request, options: .init())
  }

  public func expungeSupportEventSubscription(
    request: ExpungeSupportEventSubscriptionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func expungeSupportEventSubscription(
    name: Swift.String,
  ) async throws {
    let request = ExpungeSupportEventSubscriptionRequest().with {
      $0.name = name
    }
    try await self.expungeSupportEventSubscription(request: request)
  }
}
