// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The request message for the UpdateCase endpoint
public struct UpdateCaseRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The case to update.
  public var `case`: Case? = nil

  /// A list of attributes of the case that should be updated. Supported values
  /// are `priority`, `display_name`, and `subscriber_email_addresses`. If no
  /// fields are specified, all supported fields are updated.
  ///
  /// Be careful - if you do not provide a field mask, then you might
  /// accidentally clear some fields. For example, if you leave the field mask
  /// empty and do not provide a value for `subscriber_email_addresses`, then
  /// `subscriber_email_addresses` is updated to empty.
  public var updateMask: GoogleCloudWkt.FieldMask? = nil

  /// Initialize a new instance of `UpdateCaseRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateCaseRequest().with { $0.`case` = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case `case` = "case"
    case updateMask = "updateMask"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.`case` = try container.decodeIfPresent(Case.self, forKey: .`case`)
    self.updateMask = try container.decodeIfPresent(
      GoogleCloudWkt.FieldMask.self, forKey: .updateMask)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.`case`, forKey: .`case`)
    try container.encode(self.updateMask, forKey: .updateMask)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.support.v2.UpdateCaseRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
